name: Build WindUI (main)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.1"

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.2.1

      - name: Run build
        run: npm run build

      - name: Commit dist/main.lua back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/main.lua
          git commit -m "[AUTO] Upload built main.lua" || exit 0
          git push